### ISSUE TITLE
Main page interactivity

### ISSUE THREAD

**Issue by alexaspinalldev** [alexaspinalldev/Breaking-Mad#2]
Main page must include buttons to generate a new quote, and cycle the quote background

**Comment by BenWilliams89** [comment]
- [x] 2 x interactivity applied to website
- [x] one button click goes to a new page
- [x] The same button also produces a new quote from an API call
- [x] The second button generates a new background each time the button is clicked
- [x] The header button also generates a new quote and background

**Comment by BenWilliams89** [comment]
each of the interactivity buttons have been tested and are now working
