### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by alexaspinalldev** [alexaspinalldev/Breaking-Mad#6]
The Readme should be spectacular and full featured

**Comment by BenWilliams89** [comment]
- [ ] add introduction to readme
- [ ] add Key objectives
- [ ] add user stories
- [x] add wireframe
- [ ] add colours & fonts
- [x] add testing scores
- [ ] add am i responsive image 
- [ ] add future additions
- [ ] add how we used AI
- [ ] add Imagery
- [ ] Add website features overview
- [ ] technology used
- [ ] deployment
- [ ] credits
